import type { Metadata } from 'next';
import { HOME_OG_IMAGE_URL } from '@/lib/constants';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Footer from '@/app/components/footer';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Urodziny Ilony',
	description: 'Generated by create next app',
	openGraph: {
		images: [HOME_OG_IMAGE_URL],
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<head>
				<link rel='icon' href='globe.svg' />
			</head>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<div className='min-h-screen'>{children}</div>
				<Footer />
			</body>
		</html>
	);
}
